# Generated by Django 3.2.2 on 2022-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grado',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
