# Generated by Django 3.2.2 on 2022-09-29 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pasantia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pasantia.models.entidad_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='PostPasantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=50, unique=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_limite', models.DateTimeField()),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=pasantia.models.user_directory_path_file)),
                ('cantidad_insc', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('entidad_pert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad', to='pasantia.entidad')),
                ('pasantia_pert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad', to='pasantia.postpasantias')),
            ],
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadopas', models.CharField(choices=[('REVISION', 'REVISION'), ('FINALIZADO', 'FINALIZADO')], default='REVISION', max_length=20)),
                ('estadoest', models.CharField(choices=[('RECHAZADO', 'RECHAZADO'), ('PENDIENTE', 'PENDIENTE'), ('ACEPTADO', 'ACEPTADO')], default='PENDIENTE', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postpasantia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pasantia.postpasantias')),
            ],
        ),
    ]
