# Generated by Django 3.2.2 on 2022-09-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasantia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpasantias',
            name='entidad_pert',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='pasantia.entidad'),
            preserve_default=False,
        ),
    ]
