# Generated by Django 3.2.2 on 2022-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasantia', '0003_alter_postpasantias_entidad_pert'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpasantias',
            name='estado',
            field=models.CharField(choices=[('REVISION', 'REVISION'), ('FINALIZADO', 'FINALIZADO')], default='REVISION', max_length=20),
        ),
    ]
