# Generated by Django 3.2.2 on 2022-10-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasantia', '0006_unidad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='estado',
            field=models.CharField(choices=[('REVISION', 'REVISION'), ('ASIGNADO', 'ASIGNADO')], default='REVISION', max_length=20),
        ),
    ]
